language: go
sudo: required
services:
  - docker

env:
  global:
    - CURRENT_GO_VERSION="1.7.4"

go:
  - 1.6.4
  - 1.7.4
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/philwinder/gocoverage
  - go get github.com/kisielk/errcheck
  - curl -SL https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz | tar -xzC $GOPATH/bin

install: go get -t ./...

script:
  - go test -v ./...
  - if [ "$TRAVIS_GO_VERSION" = "$CURRENT_GO_VERSION" ]; then go test -race -v ./...; fi
  - go vet ./...
  - errcheck ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [ "$TRAVIS_GO_VERSION" = "$CURRENT_GO_VERSION" ]; then
      gocoverage && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_GO_VERSION" = "$CURRENT_GO_VERSION" ]; then
      rocker build --auth "$DOCKER_USERNAME:$(echo $DOCKER_PASSWORD | base64 -d)" --pull --meta --push;
    fi
